/-
  CatLab -- Free Categories

  The free category on a directed graph (quiver). Objects are nodes,
  morphisms are paths (including the empty path = identity).

  This is the left adjoint to the forgetful functor Cat → Quiv.
-/

import Catlab.Core.Theory

namespace CatLab

/-- A quiver (directed graph): a set of nodes and directed edges. -/
structure Quiver where
  /-- Node names -/
  nodes : List Name
  /-- Edges: (name, source node, target node) -/
  edges : List (Name × Name × Name)
  deriving Repr, Inhabited

/-- Compute the free category on a quiver.

    Objects: nodes of the quiver.
    Morphisms: generating edges (the free category is presented by
      generators = edges and no relations).
    Axioms: none (this is the free category). -/
def freeCategory (q : Quiver) : Theory :=
  let objects := q.nodes.map fun n =>
    { id := { name := n, index := 0, kind := .sort }
      description := s!"Node {n}" : Generator0 }

  let morphisms := q.edges.map fun (e, src, tgt) =>
    { id := { name := e, index := 0, kind := .morphism }
      domain := .atom { name := src, index := 0, kind := .sort }
      codomain := .atom { name := tgt, index := 0, kind := .sort }
      description := s!"Edge {e} : {src} → {tgt}" : Generator1 }

  { name := "Free"
    doctrine := { doctrine := .Category }
    objects := objects
    morphisms := morphisms
    axioms := [] }

/-- Extract the free category generated by a theory's generators,
    forgetting all axioms/relations. This is the "path category"
    of the underlying quiver of generators.

    Objects: same as the theory.
    Morphisms: same generators as the theory.
    Axioms: empty (all relations are dropped). -/
def pathCategory (t : Theory) : Theory :=
  { name := s!"Path({t.name})"
    doctrine := { doctrine := .Category }
    objects := t.objects
    morphisms := t.morphisms
    axioms := [] }

/-- Convert a Theory's generators into a Quiver (the underlying graph). -/
def Theory.toQuiver (t : Theory) : Quiver :=
  { nodes := t.objects.map (·.id.name)
    edges := t.morphisms.filterMap fun m =>
      match m.domain, m.codomain with
      | .atom src, .atom tgt => some (m.id.name, src.name, tgt.name)
      | _, _ => none }

end CatLab
